blog/urls.py
from django.urls import path
from . import views

app_name = 'blog'

urlpatterns =[
    path('', views.all_posts, name='all_posts'),
    #path('', views.PostListView, name="all_posts"),
    #path('tag/<slug:tag_slug>', ),
    path('<int:year>/<int:month>/<int:day>/<slug:post>/', views.post_detail, name='post_detail')
]

blogsite/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls import static

urlpatterns = [
    path('', include('pages.urls', namespace='pages')),
    path('admin/', admin.site.urls),
    path('blog/', include('blog.urls', namespace='blog')),
] 

pages/urls.py
from django.urls import path, include
from . import views

app_name = 'pages'

urlpatterns = [
    path('contact/', views.contact, name='contact')
]

blog/models.py
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User
from django.urls import reverse

#tags
from taggit.managers import TaggableManager

class PublishedManager(models.Manager):
    def get_queryset(self):
        return super(PublishedManager, self).get_queryset().filter(status='published')

class Post(models.Model):
    STATUS_CHOICE = (
        ('draft','Draft'),
        ('published', 'Published')
    )

    title = models.CharField(max_length=250)
    slug = models.SlugField(max_length=250, unique_for_date='publish')
    author = models.ForeignKey(User, on_delete=models.CASCADE, related_name='blog_posts')
    # add wysiwyg editor!
    body = models.TextField()

    publish = models.DateTimeField(default=timezone.now)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    status = models.CharField(max_length=10, choices=STATUS_CHOICE, default='draft')

    objects = models.Manager()
    published = PublishedManager()

    #tags 
    tags = TaggableManager()

    def get_absolute_url(self):
        return reverse('blog:post_detail', args=[self.publish.year, self.publish.month, self.publish.day, self.slug])

    class Meta:
        ordering = ('-publish',)

        def __str__(self):
            return self.title


class Comment(models.Model):
    post = models.ForeignKey(Post, on_delete=models.CASCADE, related_name='comments')
    name = models.CharField(max_length=80)
    email = models.EmailField()
    body = models.TextField()
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    active = models.BooleanField(default=True)

    class Meta:
        ordering = ('created',)

    def __str__(self):
        return 'Comment by {} on {}'.format(self.name, self.post)
    

pages/models.py
from django.db import models

# Create your models here.

blog/forms.py
from .models import Comment
from django import forms

class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('name', 'email', 'body')

pages/forms.py
from django import forms

class ContactForm(forms.Form):
    name = forms.CharField(max_length=40)
    email = forms.EmailField()
    body = forms.CharField(required=False,widget=forms.Textarea)

blog/views.py
from django.shortcuts import render, get_object_or_404
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.views.generic import ListView
from .models import Post, Comment
from .forms import CommentForm

from taggit.models import Tag

#class PostListView(ListView):
#    queryset = Post.published.all()
#    context_object_name = 'posts'
#    paginate_by = 3
#    template_name = 'blog/post/all.html'

def all_posts(request, tag_slug=None):
    object_list = Post.published.all()
    
    #tags
    tag = None
    if tag_slug:
        tag = get_object_or_404(Tag, slug=tag_slug)
        object_list = object_list.filter(tags__in=[tag])        

    #paginator
    paginator = Paginator(object_list, 3)
    page = request.GET.get('page')
    try:
        posts = paginator.page(page)
    except PageNotAnInteger:
        posts = paginator.page(1)
    except EmptyPage:
        posts = paginator.page(paginator.num_pages)

    context = {
        'posts': posts,
        'page' : page,
        'tag': tag,
    }
    
    return render(request, 'blog/post/all.html', context)

def post_detail(request, year, month, day, post):
    post = get_object_or_404(Post, slug=post, status='published', publish__year=year, publish__month=month, publish__day=day)

    new_comment = None

    #active comments
    comments = post.comments.filter(active=True)
    if request.method == "POST":
        comment_form = CommentForm(data=request.POST)

        if comment_form.is_valid():
            new_comment = comment_form.save(commit=False)
            new_comment.post = post
            new_comment.save()
    else:
        comment_form = CommentForm()

    context = {
        'post':post,
        'comments': comments,
        'new_comment': new_comment,
        'comment_form': comment_form,
    }

    return render(request, 'blog/post/detail.html', context)

pages/views.py
from django.shortcuts import render
from .forms import ContactForm

def contact(request):
    if request.method == "POST":
        form = ContactForm(request.POST)
        if form.is_valid():
            cd = form.cleaned_data
    else:
        form = ContactForm()

    context = {
        'form': form
    }
    return render(request, 'pages/contact.html', context)

blog/templates/base.html
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>{% block title %}Blog{% endblock %}</title>
    <link rel="stylesheet" href="{% static 'css/blog.css' %}">
</head>
<body>
    <div id="header">
        <h1>Blog</h1>
        <a href="{% url 'pages:contact' %}">
            <p>Kontakt</p>
        </a>
    </div>

    <div id="content">
        {% block content %}
        {% endblock %}
    </div>

    {% include 'paginator.html' with page=posts %}

</body>
</html>

blog/templates/blog/post/all.html
{% extends 'base.html' %}
{% block title %}Blog All Posts{% endblock %}

{% block content %}
    {% for post in posts %}
        <h2>
            <a href="{{ post.get_absolute_url }}">{{post.title}}</a>
        </h2>
        <p class="date">
            Published {{post.publish}} by <b{{post.author}}
        </p>
        {{ post.body|truncatewords:30|linebreaks }}
    {% endfor %}
{% endblock %}

blog/templates/blog/post/detail.html
{% extends 'base.html' %}
{% block title %} {{post.title}} | DigitalJunkie {% endblock %}
{% block content %}
<div id="post">
    <h2>
        {{ post.title }}
    </h2>

    <p class="tags">
        Tags: {{ post.tags.all|join:", " }}
    </p>
    
    <i class="date">
        Published {{post.publish}} by <b>{{post.author}}</b>
    </i>

    <div class="post_body">
    {{ post.body }}
    </div>
    
    <hr>
</div>

<div id="commentarea">
    {% with comments.count as total_comments %}
        <h2>
            {% if total_comments == 1 %}
                {{ total_comments }} komentarz
            {% elif total_comments == 0 %}
                {{ total_comments }} komantarzy
            {% elif total_comments >= 5 %}
                {{ total_comments }} komentarzy
            {% else %}
                {{ total_comments }} komantarze
            {% endif %}
        </h2>
    {% endwith %}

        {% for comment in comments %}
            <div class="comment">
                <p class="info">
                    <b>{{ comment.name }}</b>, {{ comment.created }}
                </p>
                    {{ comment.body|linebreaks }}
            </div>
            {% empty %}
                <p>Nie ma jeszcze żadnych komentarzy.</p>
        {% endfor %}
</div>

    <div id="addcommentarea">
        <h2>Dodaj nowy komentarz:</h2>
        <form action="." method="post">
            {{ comment_form.as_p }}
            {% csrf_token %}
            <p><input type="submit" value="Dodaj komentarz"></p>
        </form>
    </div>

    <a href="{% url 'blog:all_posts' %}">Z powrotem</a>
{% endblock %}

blog/templates/paginator.html
<div class="pagination">
    <span class="step-links">
        
        {% if page.has_previous %}
            <a href="?page={{ page.previous_page_number }}">Poprzednia strona</a>
        {% endif %}
        
        <span class="current">
            Strona {{ page.number }} z {{ page.paginator.num_pages }}.
        </span>

        {% if page.has_next %}
            <a href="?page={{ page.next_page_number }}">Następna</a>
        {% endif %}
    </span>
</div>

pages/templates/base_pages.html
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    {% block title %}{% endblock %}
</head>
<body>
    {% block content %}
    {% endblock %}

    <br>
    <hr>
    <a href="{% url 'blog:all_posts' %}">Z powrotem</a>
</body>
</html>

pages/templates/pages/contact.html
{% extends 'base_pages.html' %}
{% block title %}
    <title>Kontakt</title>
{% endblock %}

{% block content %}
    {% if sent %}
        <h1>E-mail wysłany!</h1>
    {% else %}
        <h1>Kontakt</h1>
        <form action="." method="post">
            {{ form.as_p }}
            {% csrf_token %}
            <input type="submit" value="Wyślij" />
        </form>
    {% endif %}
{% endblock %}